export default [
  {
    id: 'coffee',
    name: 'Cà Phê',
    items: [
      {
        id: 0,
        name: 'Latte - This is a long text - Please use truncate the text if it is longer than 2 lines',
        description: 'Note - This text is not longer than 1 line',
        price: 99000,
        oldPrice: 90000,
        img: '270_crop_LATTE.png',
      },
      {
        id: 1,
        name: 'Cappuccino',
        description: 'Cappuccino',
        price: 39000,
        oldPrice: 49000,
        img: '270_crop_CAPPUCINO.png',
      },
      {
        id: 2,
        name: 'Americano',
        description: 'Americano',
        price: 60000,
        img: '270_crop_AMERICANO.png',
      },
      {
        id: 3,
        name: 'Espresso',
        description: 'Espresso',
        price: 60000,
        img: '270_crop_ESPRESSO.png',
      },
      {
        id: 4,
        name: 'Caramel Macchiato',
        description: 'Caramel Macchiato',
        price: 60000,
        img: '270_crop_CARAMEL-MACCHIATO.png',
      },
    ],
  },
  {
    id: 'bread',
    name: 'Bánh Mì',
    items: [
      {
        id: 0,
        name: 'Xíu Mại',
        description: 'Pork Meatball',
        price: 19000,
        img: '270_crop_BMXIUMAI.png',
      },
      {
        id: 1,
        name: 'Chả Lụa Xá Xíu',
        description: 'Roast Pork & Pork Sausage',
        price: 19000,
        img: '270_crop_BMCHALUAXAXIU.png',
      },
      {
        id: 2,
        name: 'Gà Xé Nước Tương',
        description: 'Roast Chicken',
        price: 19000,
        img: '270_crop_BMGAXE.png',
      },
      {
        id: 3,
        name: 'Thịt Nướng',
        description: 'Grilled Pork',
        price: 19000,
        img: '270_crop_BMTHITNUONG.png',
      },
    ],
  },
  {
    id: 'cake',
    name: 'Bánh Ngọt',
    items: [
      {
        id: 0,
        name: 'Bánh Mousse Cacao',
        description: 'Cocoa Mousse Cake',
        price: 29000,
        img: '270_crop_MOUSSECACAO.png',
      },
      {
        id: 1,
        name: 'Bánh Mousse Đào',
        description: 'Peach Mousse Cake',
        price: 29000,
        img: '270_crop_MOUSSEDAO.png',
      },
      {
        id: 2,
        name: 'Bánh Sô-cô-la Highlands',
        description: 'Highlands Chocolate Bomb',
        price: 29000,
        img: '270_crop_SOCOLAHL.png',
      },
    ],
  },
  {
    id: 'Tea',
    name: 'Trà',
    items: [
      {
        id: 0,
        name: 'Trà Thạch Vãi',
        description: 'Lychee Tea',
        price: 39000,
        img: '270_crop_TRATHACHVAI_1.png',
      },
      {
        id: 1,
        name: 'Trà Thạch Đào',
        description: 'Peach Jelly Tea',
        price: 39000,
        img: '270_crop_TRATHACHDAO.png',
      },
      {
        id: 2,
        name: 'Trà Thanh Đào',
        description: 'Peach Lemongrass Tea',
        price: 39000,
        img: '270_crop_TRATHANHDAO.png',
      },
      {
        id: 3,
        name: 'Trà Sen Vàng',
        description: 'Golden Lotus Tea',
        price: 39000,
        img: '270_crop_TRASENVANG.png',
      },
    ],
  },
  {
    id: 'other',
    name: 'Khác',
    items: [
      {
        id: 0,
        name: 'Phin Inox',
        description: 'Phin Inox',
        price: 80000,
        img: '270_crop_PHININOX.png',
      },
      {
        id: 1,
        name: 'Ly Sứ Mosaic',
        description: 'Mosaic Mug',
        price: 29000,
        img: '270_crop_LYSU.png',
      },
    ],
  },
];
